### ISSUE TITLE
Basic About Page

### ISSUE THREAD

**Issue by J3RN** [CWDG/design-circle-old#2]
This will be a static page, but should be visually appealing. For full details, see [the README](https://github.com/CWDG/design-circle/blob/master/README.md).

Feel free to work with someone!

**Comment by andyklimczak** [comment]
I'm here too; making branch `about_page`

**Comment by J3RN** [comment]
I just added you

**Comment by jae-lee** [comment]
@J3RN Is it not possible to assign issues to two people?

**Comment by jae-lee** [comment]
Lame.

**Comment by J3RN** [comment]
Yeah, that's what I thought.
